spring:
  application:
    name: itoken-service-admin
server:
  port: 8201

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
datasource:
  druid:
    url: jdbc:mysql//localhost:3306/itoken-service-admin
    username: root


