spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 120.77.253.48
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://120.77.253.48:8762/eureka/,http://120.77.253.48:8861/eureka/,http://120.77.253.48:8961/eureka/