spring:
  application:
    name: itoken-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.77.253.48:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itoken-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: itoken-web-admin-feign