spring:
  application:
    name: itoken-service-admin
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/itoken-service-admin
      username: root
      password: 1096150741
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8201

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
mybatis:
  type-aliases-package: cn.xp1997.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml