spring:
  application:
    name: itoken-eureka


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://120.77.253.48:8761/eureka/,http://120.77.253.48:8861/eureka/,http://120.77.253.48:8961/eureka/