spring:
  application:
    name: itoken-eureka
server:
  port: 8861

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8861/eureka/,http://localhost:8961/eureka/
  server:
    enableSelfPreservation: false